name: Trigger Multiple Hugging Face Spaces with Random Delay

on:
  schedule:
    # 每隔16小时触发一次
    - cron: '0 */16 * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get random delay
        id: random_delay
        run: echo "::set-output name=delay::$((RANDOM % 120))"
      
      - name: Delay execution
        run: sleep ${{ steps.random_delay.outputs.delay }}m

      - name: Wake up Hugging Face Spaces
        run: |
          for url in https://efan3536-sillytavern.hf.space https://efan3536-clewd.hf.space https://naki123-sillytavern.hf.space https://efan3536-jiuguan.hf.space https://lang03383-tteesstt.hf.space https://naki123-cheshi2.hf.space; do
            curl -X GET "$url"
            sleep 5
          done
